# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate APK

on:
  push:
    branches: [ master,addCI,test-workflow ]
  # pull_request:
  #   branches: [ master,addCI  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Setup android
      uses: android-actions/setup-android@v2
    - run: npm install -g cordova ionic
    - run: npm install -g try-thread-sleep
    - run: echo $ANDROID_HOME
    - run: cordova platform rm android
      working-directory: android
    - run: cordova platform add android
      working-directory: android
    - name: Reset the Config
      run: git checkout android/platforms/android/CordovaLib/src/org/apache/cordova/ConfigXmlParser.java
    - name: Uninstall  build-tool version 31.0.0
      run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager --uninstall 'build-tools;31.0.0'
    - run: cordova build android
      working-directory: android
    - name: Uplaod Artifact
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: android/platforms/android/app/build/outputs/apk/debug/app-debug.apk
      if: always()



